name: Deploy to cPanel via SFTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SERVER_URL }}
          port: 22
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local_path: ./       # path in your repo you want to upload
          remote_path: ${{ secrets.CPANEL_DIR }}  # remote folder
          sftp_only: true
